---
title: "Homework3"
author: "Julissa Duenas"
date: "2/24/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages('ggridges')
#install.packages('superheat')
library(tidyverse)
library(ROCR)
library(tree)
library(maptree)
library(class)
library(lattice)
library(ggridges)
library(superheat)
#install.packages('dendextend')
library(dendextend)
```

```{r message=FALSE}
drug_use <- read_csv('drug.csv',
col_names = c('ID','Age','Gender','Education','Country','Ethnicity','Nscore',
              'Escore','Oscore','Ascore','Cscore','Impulsive','SS','Alcohol',
              'Amphet','Amyl','Benzos','Caff','Cannabis','Choc','Coke','Crack',
              'Ecstasy','Heroin','Ketamine','Legalh','LSD','Meth','Mushrooms',
              'Nicotine','Semer','VSA'))
```

Question 1
```{r}
drug_use <- drug_use %>% mutate_at(as.ordered, .vars=vars(Alcohol:VSA))
drug_use <- drug_use %>%mutate(Gender = factor(Gender, 
                                               labels=c("Male", "Female"))) %>% 
  mutate(Ethnicity = factor(Ethnicity, labels=c("Black", "Asian", "White","Mixed:White/Black",
                                                "Other","Mixed:White/Asian","Mixed:Black/Asian")))%>%
  mutate(Country = factor(Country,labels=c("Australia", "Canada", "New Zealand","Other", "Ireland", 
                                           "UK", "USA")))
```
(a)
```{r}
drug_use <- drug_use%>%
  mutate(recent_cannabis_use=factor(ifelse(Cannabis>='CL3','Yes','No'),levels=c('No','Yes')))
class(drug_use$recent_cannabis_use)
```

(b)
```{r}
drug_use_subset <- drug_use %>% select(Age:SS, recent_cannabis_use)

train <- sample(1:nrow(drug_use_subset),1500)
drug_use_train <- drug_use_subset[train,]
drug_use_test <- drug_use_subset[-train,]

dim(drug_use_train)
dim(drug_use_test)
```

(c)
```{r}
rec.can.use.glm <- glm(recent_cannabis_use~.,data = drug_use_train,family = binomial)
summary(rec.can.use.glm)
```


Question 2
```{r}
tree_parameters = tree.control(nobs=nrow(drug_use_train), minsize=10, mindev=1e-3)
```

(a)
```{r}
set.seed(2)
tree.drug_use <- tree(recent_cannabis_use~.,data=drug_use_train,control=tree_parameters)
cv=cv.tree(tree.drug_use,FUN=prune.misclass,K=10)
best.cv=cv$size[max(which(cv$dev==min(cv$dev)))]
best.cv
```

(b)
```{r}
prune.drug_use <- prune.misclass(tree.drug_use,best=best.cv)
draw.tree(prune.drug_use,nodeinfo = TRUE,cex=.4)
```

The first variable that is split is 'Country'

(c)
```{r}
set.seed(2)
drug.pred <- predict(prune.drug_use,drug_use_test,type='class')
error <- table(drug.pred,drug_use_test$recent_cannabis_use)
error
TPR=error[2,2]/(error[2,2]+error[1,2])
FPR=error[2,1]/(error[2,1]+error[1,1])
TPR
FPR
```

Question 3
(a)
```{r}
prob.glm <- predict(rec.can.use.glm,drug_use_test,type = 'response')
prob.tree <- predict(prune.drug_use,drug_use_test,type='vector')
pred.glm <- prediction(prob.glm,drug_use_test$recent_cannabis_use)
pred.tree <- prediction(prob.tree[,2],drug_use_test$recent_cannabis_use)
roc.glm <- performance(pred.glm,measure = 'tpr',x.measure = 'fpr')
roc.tree <- performance(pred.tree,measure = 'tpr',x.measure = 'fpr')
plot(roc.glm,col=2,lwd=3,main='ROC CURVE')
plot(roc.tree,col=4,lwd=3,main='ROC CURVE',add=TRUE)
abline(0,1)
```

(b)
```{r}
auc.glm <- performance(pred.glm,'auc')@y.values
auc.tree <- performance(pred.tree,'auc')@y.values
auc.glm
auc.tree
```
The logistic regression model has a slightly larger AUC

Question 4
```{r message=FALSE, warning=FALSE}
leukemia_data <- read_csv("leukemia_data.csv")
```

(a)
```{r message=TRUE, warning=TRUE}
leukemia_data <- leukemia_data%>%mutate(Type=factor(Type))
table(leukemia_data$Type)
```
BCR-ABL occurs the least in this data

(b)
```{r}
pr.leuk <- prcomp(leukemia_data[,-1],scale=TRUE,center=TRUE)
pr.var <- pr.leuk$sdev^2
pve <- pr.var/sum(pr.var)
cumulative_pve <- cumsum(pve)
## This will put the next two plots side by side
par(mfrow=c(1, 2))
## Plot proportion of variance explained
plot(pve, type="l", lwd=3)
plot(cumulative_pve, type="l", lwd=3)
```

(c)
```{r}
rainbow_colors <- rainbow(7)
plot_colors <- rainbow_colors[leukemia_data$Type]
```
```{r}
plot(pr.leuk$x[,1:2],col=plot_colors,cex=.5)
text(pr.leuk$x[,1:2],labels = leukemia_data$Type,cex=.5,col=plot_colors)
head(pr.leuk$x[,1:2])
head(sort(abs(pr.leuk$rotation[,1]),decreasing = TRUE))
```
T-ALL looks to be the most separated. SEMA3F has the highest absolute loading value.

(f)
```{r}
leukemia_subset <- leukemia_data%>%filter(Type=='T-ALL'|Type=='TEL-AML1'|Type=='Hyperdip50')
dis <- dist(leukemia_subset[,-1],method='euclidean')
leukemia.hc <- hclust(dis,method='complete')
dend1 <- as.dendrogram(leukemia.hc)
dend1 <- color_branches(dend1,k=3)
dend1 <- color_labels(dend1,k=3)
dend1 <- set(dend1,'labels_cex',0.1)
dend1 <- set_labels(dend1,labels=leukemia_subset$Type[order.dendrogram(dend1)])
plot(dend1,horiz=T,main='Dendogram colored by three clusters')

dend2 <- as.dendrogram(leukemia.hc)
dend2 <- color_branches(dend2,k=5)
dend2 <- color_labels(dend2,k=5)
dend2 <- set(dend2,'labels_cex',0.1)
dend2 <- set_labels(dend2,labels=leukemia_subset$Type[order.dendrogram(dend2)])
plot(dend2,horiz=T,main='Dendogram colored by five clusters')

```

